language: ruby
rvm:
  - 2.1.2

source 'https://rubygems.org'

gem 'rake'
gem 'rspec'

task :default => [:rspec]
begin
  require 'rspec/core/rake_task'
  RSpec::Core::RakeTask.new(:spec) do |spec|
    spec.pattern = 'spec/*_spec.rb'
    spec.rspec_opts = ['-cfs']
  end
rescue LoadError => e
end
